# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cgr.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cgr.proto',
  package='linden',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tcgr.proto\x12\x06linden\"\xa7\x01\n\x0e\x43GRStartParams\x12\r\n\x05\x63ur_A\x18\x01 \x01(\x01\x12\x13\n\x0bstep_length\x18\x02 \x01(\x01\x12\x17\n\x0f\x64\x65nsity_penalty\x18\x03 \x01(\x01\x12*\n\x05\x63\x65lls\x18\x04 \x03(\x0b\x32\x1b.linden.CGRStartParams.Cell\x1a,\n\x04\x43\x65ll\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02\x64x\x18\x02 \x01(\x03\x12\n\n\x02\x64y\x18\x03 \x01(\x03\x62\x06proto3'
)




_CGRSTARTPARAMS_CELL = _descriptor.Descriptor(
  name='Cell',
  full_name='linden.CGRStartParams.Cell',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='linden.CGRStartParams.Cell.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dx', full_name='linden.CGRStartParams.Cell.dx', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='dy', full_name='linden.CGRStartParams.Cell.dy', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=145,
  serialized_end=189,
)

_CGRSTARTPARAMS = _descriptor.Descriptor(
  name='CGRStartParams',
  full_name='linden.CGRStartParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='cur_A', full_name='linden.CGRStartParams.cur_A', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step_length', full_name='linden.CGRStartParams.step_length', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='density_penalty', full_name='linden.CGRStartParams.density_penalty', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cells', full_name='linden.CGRStartParams.cells', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_CGRSTARTPARAMS_CELL, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=189,
)

_CGRSTARTPARAMS_CELL.containing_type = _CGRSTARTPARAMS
_CGRSTARTPARAMS.fields_by_name['cells'].message_type = _CGRSTARTPARAMS_CELL
DESCRIPTOR.message_types_by_name['CGRStartParams'] = _CGRSTARTPARAMS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CGRStartParams = _reflection.GeneratedProtocolMessageType('CGRStartParams', (_message.Message,), {

  'Cell' : _reflection.GeneratedProtocolMessageType('Cell', (_message.Message,), {
    'DESCRIPTOR' : _CGRSTARTPARAMS_CELL,
    '__module__' : 'cgr_pb2'
    # @@protoc_insertion_point(class_scope:linden.CGRStartParams.Cell)
    })
  ,
  'DESCRIPTOR' : _CGRSTARTPARAMS,
  '__module__' : 'cgr_pb2'
  # @@protoc_insertion_point(class_scope:linden.CGRStartParams)
  })
_sym_db.RegisterMessage(CGRStartParams)
_sym_db.RegisterMessage(CGRStartParams.Cell)


# @@protoc_insertion_point(module_scope)
